### ISSUE TITLE
Function_1: Bootstrapped distribution

### ISSUE THREAD

**Issue by zackt113** [UBC-MDS/strapvizpy#10]

**Comment by BooleanJulien** [comment]
@gauthampughazhendhi I think I see where you were going with adding compatibility for various sample statistics like the variance and sd. 

please refer to my slack post https://ubc-mds.slack.com/archives/C24HUP6SU/p1642490772118700

Do you know if it's the same procedure to get the CIs for statistics other than the mean?

My googling of this topic was not fruitful

**Comment by gauthampughazhendhi** [comment]
@BooleanJulien I think once you generate a bootstrap distribution of a particular estimator your CIs will depend only on that distribution. So, I think based on my knowledge you can use the same CI formula to derive the CI bounds of the distribution irrespective of the estimator.

**Comment by BooleanJulien** [comment]
I will update my function today for compatibility
