### ISSUE TITLE
Function_3: Density_ci_plot

### ISSUE THREAD

**Issue by zackt113** [UBC-MDS/strapvizpy#12]

**Comment by voremargot** [comment]
Hey @zackt113, we should coordinate what are imports are for plot and table creation so the method is the same for the package! I noticed that you are calling Julian's function within your function, which means the user inputs all the original data and parameters into your function. My table function just calls the dictionary that is outputted by Julian's function. Do you have a preference of which way we should do it? I see benefits to both....  Check out the feature/table_creation branch if you want to see how I was doing it.

**Comment by zackt113** [comment]
> Hey @zackt113, we should coordinate what are imports are for plot and table creation so the method is the same for the package! I noticed that you are calling Julian's function within your function, which means the user inputs all the original data and parameters into your function. My table function just calls the dictionary that is outputted by Julian's function. Do you have a preference of which way we should do it? I see benefits to both.... Check out the feature/table_creation branch if you want to see how I was doing it.

Hey @voremargot, I think it would be a good idea to apply to your function as users don't have to input all those things again. But for my function, my concern is that users have to call Julien's function with the parameter "pass_dist = True". Also, if users only want a plot, maybe asking them to input all parameters would be great. For my function, I slightly prefer my way as it provides more flexibility? But I could also add a TypeError to ask users to include the parameter? I actually don't have a strong preference over those two ways. What do you think?

**Comment by zackt113** [comment]
@gauthampughazhendhi, I know you are not involved in this issue, but I would like to hear some of your thoughts if you got some time, haha. :)
