### ISSUE TITLE
Create to project structure

### ISSUE THREAD

**Issue by voremargot** [UBC-MDS/strapvizpy#2]
- [x] create repo structure using cookiecutter
- [x] Edit CONDUCT.md to include the code of conduct
- [x] Develop collaboration strategy and edit CONTRIBUTING.md to reflect the strategy
- [x] Outline the packages we are building in the README.md file.

**Comment by BooleanJulien** [comment]
The default conduct and contributing looked good to me. I am inclined to keep them as is given how much other stuff I have to do this week! The instructions seem to indicate that this is an option for us.
