### ISSUE TITLE
Function specifications

### ISSUE THREAD

**Issue by voremargot** [UBC-MDS/strapvizpy#3]
- [x] Set up empty functions with full function documentation for bootstrapping
- [x] Set up empty function with full function documentation for summary statistics
- [x] Set up empty function with full function documentation for plotting
- [x] Set up empty function with full documentation for table creation

**Comment by voremargot** [comment]
As I looked over Zack's  doc strings, I was thinking that, for the table, we might  make the statistics optional parameters so the user can pick and choose what will be in the final table. This would make it more flexible for the user as well as add some complexity to the function. Thoughts @zackt113 @gauthampughazhendhi @BooleanJulien

**Comment by gauthampughazhendhi** [comment]
@voremargot that's a good idea, but can we decide on the set of statistics that we should display on the table, any specific stats you have in mind? One thing I would suggest would be the standard error.

**Comment by voremargot** [comment]
I am thinking for sure mean, standard deviation, CI upper, CI lower, selected alpha. 
Any other statistics that might be helpful in  a publication or report (i.e quartiles, sample size,  bootstrapping reps)?

**Comment by BooleanJulien** [comment]
Personally I think the table should be limited to statistics on the sampling distribution of the statistic we are estimating (mean, sd, CI bounds with alpha)

The info that was relevant to the process of estimation (sample size, bootstrapping reps) could perhaps go into the title of the table produced?

**Comment by zackt113** [comment]
@voremargot Yeah, sure, We could add some optional parameters to make it more flexible. And I agree with @BooleanJulien that we should stick with the statistics on the sampling distribution as the input distribution is the bootstrapped samples. What about adding standard error, sample size, sample mean, selected alpha? Anything add-on?

**Comment by zackt113** [comment]
Also, if I would like to change something that is different from the previous pull request. Do you guys know how should I do that? Should I close the previous pull request and then create a new one?

**Comment by BooleanJulien** [comment]
Also @gauthampughazhendhi in generating the bootsrapped distributions, can we have a default for "n" (size of each bootstrap sample) be "auto" ?

This would be the length of the input vector/column by default.

**Comment by BooleanJulien** [comment]
Yeah @voremargot @gauthampughazhendhi in regards to @zackt113's comment, if we have minor requested changes on a PR, what should the process be? Should we still accept the PR and make subsequent changes or request a new PR?

**Comment by voremargot** [comment]
If you want to make changes to a pull request, just make the changes and push them to the repo and they should show up in the request that is already open! No need to delete the request and make a new one.  Just comment on the request once the changes are made so we know we can merge them.

**Comment by voremargot** [comment]
Also I am totally happy with the suggested statistics! Lets do it!

**Comment by gauthampughazhendhi** [comment]
@BooleanJulien @zackt113 as @voremargot correctly mentioned, just add your changes to the same feature branch, the PR would be automatically updated and you can find the changes under **files** tab of the PR.

**Comment by gauthampughazhendhi** [comment]
> Also @gauthampughazhendhi in generating the bootsrapped distributions, can we have a default for "n" (size of each bootstrap sample) be "auto" ?
> 
> This would be the length of the input vector/column by default.

@BooleanJulien  Yes, I am doing it. Thanks for the suggesstion.

**Comment by gauthampughazhendhi** [comment]
@zackt113 the stats you mentioned looks good to me.
