### ISSUE TITLE
Milestone 1 Regrade

### ISSUE THREAD

**Issue by tiffyl** [UBC-MDS/strapvizpy#33]
Hi Group 22, 

I've revisited your milestone 1 as part of the regrade request regarding my mark deductions.

As for the marks regarding github commits, that was my mistake and I have corrected that now. However, as I've checked recently, a couple things have been pushed to the main branch (updating dependencies & changing file names). Just as a reminder, even if it's not function related, it is still best to not push to main branch, otherwise you guys have been doing great with using your branches.  

As for the reason of "each function should have it's own file ", after consideration, I will not deduct the marks in this case for the following reasons:
- You've mentioned that Tiffany has said that it is okay to group functions based on their use and relation, which I agree.
- The rubric specifically looks at the quality of the function (ex. has the function been declared & are docstrings included - which both were completed by your group)

I would just like to add that although it is true that it's okay/good to put related functions into the same file, this would be more applicable if the same person was to work on all the related functions. However, in this case, I thought having individual function files would eliminate any potential complications, hence why I took off marks in the first place. Again, since this is not asked for specifically for this project, I will leave that up to you guys and marks will not be deducted.

Please check that your marks has been updated on Canvas. Thanks!

Cheers,
Tiff

**Comment by gauthampughazhendhi** [comment]
@tiffyl thank you for the update, really appreciate the comments.

**Comment by voremargot** [comment]
@tiffyl  Thanks so much for looking over the grading and the explanation! I really appreciate it!
